disable test report
Signed-off-by: Benny Samir Hierl <bennysamir@posteo.de>

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -31,13 +31,13 @@ jobs:
         run: npm ci
       - name: Unit tests
         run: npm run test:unit:ci
-      - name: Test Report
-        uses: dorny/test-reporter@v1
-        if: success() || failure()
-        with:
-          name: Vitest Tests
-          path: reports/unittest.json
-          reporter: mocha-json
+      # - name: Test Report
+      #   uses: dorny/test-reporter@v1
+      #   if: success() || failure()
+      #   with:
+      #     name: Vitest Tests
+      #     path: reports/unittest.json
+      #     reporter: mocha-json
   docker:
     runs-on: ubuntu-latest
     needs:
